print("=== Seed Flywheel v0.3 ===")
print("Mike + Rex = 50/50")
print("We're learning to code and building AGI at the same time.")
print("Every time we update this, we get closer to a trillion dollars.")
print("\nType 'run' to start the next loop.")